site_name: Tangerine Documentation
repo_url: https://github.com/Tangerine-Community/TestingDocumentation
site_author: Tangerine Community
# theme:
#   name: readthedocs
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - JavaScript
#     - TypeScript
plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - smarty
